schema_version: https://raw.githubusercontent.com/hubverse-org/hubPredEvalsData/main/inst/schema/v1.0.0/config_schema.json
targets:
- target_id: wk inc flu hosp
  metrics:
  - wis
  - ae_median
  - interval_coverage_50
  - interval_coverage_95
  relative_metrics:
  - wis
  - ae_median
  baseline: UMass-AR2
  disaggregate_by:
  - location
  - reference_date
  - horizon
  - target_end_date
eval_sets:
- eval_set_name: two seasons, state level
  task_filters:
    location:
    - "01"
    - "02"
    - "04"
    - "05"
    - "06"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"
    - "13"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "23"
    - "24"
    - "25"
    - "26"
    - "27"
    - "28"
    - "29"
    - "30"
    - "31"
    - "32"
    - "33"
    - "34"
    - "35"
    - "36"
    - "37"
    - "38"
    - "39"
    - "40"
    - "41"
    - "42"
    - "44"
    - "45"
    - "46"
    - "47"
    - "48"
    - "49"
    - "50"
    - "51"
    - "53"
    - "54"
    - "55"
    - "56"
    horizon:
    - 0
    - 1
    - 2
    - 3
- eval_set_name: two seasons, US national level
  task_filters:
    location:
    - "US"
    horizon:
    - 0
    - 1
    - 2
    - 3
- eval_set_name: 2024-2025 season, state level
  task_filters:
    location:
    - "01"
    - "02"
    - "04"
    - "05"
    - "06"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"
    - "13"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "23"
    - "24"
    - "25"
    - "26"
    - "27"
    - "28"
    - "29"
    - "30"
    - "31"
    - "32"
    - "33"
    - "34"
    - "35"
    - "36"
    - "37"
    - "38"
    - "39"
    - "40"
    - "41"
    - "42"
    - "44"
    - "45"
    - "46"
    - "47"
    - "48"
    - "49"
    - "50"
    - "51"
    - "53"
    - "54"
    - "55"
    - "56"
    horizon:
    - 0
    - 1
    - 2
    - 3
    reference_date:
    - "2024-11-30"
    - "2024-12-07"
    - "2024-12-14"
    - "2024-12-21"
    - "2024-12-28"
    - "2025-01-04"
    - "2025-01-11"
    - "2025-01-18"
    - "2025-02-01"
    - "2025-02-08"
    - "2025-02-15"
    - "2025-02-22"
    - "2025-03-01"
    - "2025-03-08"
    - "2025-03-15"
    - "2025-03-22"
    - "2025-03-29"
    - "2025-04-05"
    - "2025-04-12"
    - "2025-04-19"
    - "2025-04-26"
    - "2025-05-03"
    - "2025-05-10"
    - "2025-05-17"
- eval_set_name: 2024-2025 season, US national level
  task_filters:
    location:
    - "US"
    horizon:
    - 0
    - 1
    - 2
    - 3
    reference_date:
    - "2024-11-30"
    - "2024-12-07"
    - "2024-12-14"
    - "2024-12-21"
    - "2024-12-28"
    - "2025-01-04"
    - "2025-01-11"
    - "2025-01-18"
    - "2025-02-01"
    - "2025-02-08"
    - "2025-02-15"
    - "2025-02-22"
    - "2025-03-01"
    - "2025-03-08"
    - "2025-03-15"
    - "2025-03-22"
    - "2025-03-29"
    - "2025-04-05"
    - "2025-04-12"
    - "2025-04-19"
    - "2025-04-26"
    - "2025-05-03"
    - "2025-05-10"
    - "2025-05-17"
- eval_set_name: 2023-2024 season, state level
  task_filters:
    location:
    - "01"
    - "02"
    - "04"
    - "05"
    - "06"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"
    - "13"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "23"
    - "24"
    - "25"
    - "26"
    - "27"
    - "28"
    - "29"
    - "30"
    - "31"
    - "32"
    - "33"
    - "34"
    - "35"
    - "36"
    - "37"
    - "38"
    - "39"
    - "40"
    - "41"
    - "42"
    - "44"
    - "45"
    - "46"
    - "47"
    - "48"
    - "49"
    - "50"
    - "51"
    - "53"
    - "54"
    - "55"
    - "56"
    - "72"
    horizon:
    - 0
    - 1
    - 2
    - 3
    reference_date:
    - "2023-10-21"
    - "2023-10-28"
    - "2023-11-04" 
    - "2023-11-11"
    - "2023-11-18"
    - "2023-11-25"
    - "2023-12-02" 
    - "2023-12-09"
    - "2023-12-16"
    - "2023-12-23"
    - "2023-12-30" 
    - "2024-01-06"
    - "2024-01-13"
    - "2024-01-20"
    - "2024-01-27" 
    - "2024-02-03"
    - "2024-02-10"
    - "2024-02-17"
    - "2024-02-24"
    - "2024-03-02"
    - "2024-03-09"
    - "2024-03-16"
    - "2024-03-23" 
    - "2024-03-30"
    - "2024-04-06"
    - "2024-04-13"
    - "2024-04-20"
    - "2024-04-27"
    - "2024-05-04"
    - "2024-05-11"
- eval_set_name: 2023-2024 season, US national level
  task_filters:
    location:
    - "US"
    horizon:
    - 0
    - 1
    - 2
    - 3
    reference_date:
    - "2023-10-21"
    - "2023-10-28"
    - "2023-11-04" 
    - "2023-11-11"
    - "2023-11-18"
    - "2023-11-25"
    - "2023-12-02" 
    - "2023-12-09"
    - "2023-12-16"
    - "2023-12-23"
    - "2023-12-30" 
    - "2024-01-06"
    - "2024-01-13"
    - "2024-01-20"
    - "2024-01-27" 
    - "2024-02-03"
    - "2024-02-10"
    - "2024-02-17"
    - "2024-02-24"
    - "2024-03-02"
    - "2024-03-09"
    - "2024-03-16"
    - "2024-03-23" 
    - "2024-03-30"
    - "2024-04-06"
    - "2024-04-13"
    - "2024-04-20"
    - "2024-04-27"
    - "2024-05-04"
    - "2024-05-11"
- eval_set_name: Last 4 weeks, state level
  round_filters:
    min: '2024-11-30'
    n_last: 5
  task_filters:
    location:
    - "01"
    - "02"
    - "04"
    - "05"
    - "06"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"
    - "13"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "23"
    - "24"
    - "25"
    - "26"
    - "27"
    - "28"
    - "29"
    - "30"
    - "31"
    - "32"
    - "33"
    - "34"
    - "35"
    - "36"
    - "37"
    - "38"
    - "39"
    - "40"
    - "41"
    - "42"
    - "44"
    - "45"
    - "46"
    - "47"
    - "48"
    - "49"
    - "50"
    - "51"
    - "53"
    - "54"
    - "55"
    - "56"
    - "72"
    horizon:
    - 0
    - 1
    - 2
    - 3
- eval_set_name: Last 4 weeks, US national level
  round_filters:
    min: '2024-11-30'
    n_last: 5
  task_filters:
    location:
    - "US"
    horizon:
    - 0
    - 1
    - 2
    - 3
- eval_set_name: Last 2 weeks, state level
  round_filters:
    min: '2024-11-30'
    n_last: 3
  task_filters:
    location:
    - "01"
    - "02"
    - "04"
    - "05"
    - "06"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"
    - "13"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "23"
    - "24"
    - "25"
    - "26"
    - "27"
    - "28"
    - "29"
    - "30"
    - "31"
    - "32"
    - "33"
    - "34"
    - "35"
    - "36"
    - "37"
    - "38"
    - "39"
    - "40"
    - "41"
    - "42"
    - "44"
    - "45"
    - "46"
    - "47"
    - "48"
    - "49"
    - "50"
    - "51"
    - "53"
    - "54"
    - "55"
    - "56"
    - "72"
    horizon:
    - 0
    - 1
    - 2
    - 3
- eval_set_name: Last 2 weeks, US national level
  round_filters:
    min: '2024-11-30'
    n_last: 3
  task_filters:
    location:
    - "US"
    horizon:
    - 0
    - 1
    - 2
    - 3
task_id_text:
  location:
    US: United States
    '01': Alabama
    '02': Alaska
    '04': Arizona
    '05': Arkansas
    '06': California
    '08': Colorado
    '09': Connecticut
    '10': Delaware
    '11': District of Columbia
    '12': Florida
    '13': Georgia
    '15': Hawaii
    '16': Idaho
    '17': Illinois
    '18': Indiana
    '19': Iowa
    '20': Kansas
    '21': Kentucky
    '22': Louisiana
    '23': Maine
    '24': Maryland
    '25': Massachusetts
    '26': Michigan
    '27': Minnesota
    '28': Mississippi
    '29': Missouri
    '30': Montana
    '31': Nebraska
    '32': Nevada
    '33': New Hampshire
    '34': New Jersey
    '35': New Mexico
    '36': New York
    '37': North Carolina
    '38': North Dakota
    '39': Ohio
    '40': Oklahoma
    '41': Oregon
    '42': Pennsylvania
    '44': Rhode Island
    '45': South Carolina
    '46': South Dakota
    '47': Tennessee
    '48': Texas
    '49': Utah
    '50': Vermont
    '51': Virginia
    '53': Washington
    '54': West Virginia
    '55': Wisconsin
    '56': Wyoming
    '60': American Samoa
    '66': Guam
    '69': Northern Mariana Islands
    '72': Puerto Rico
    '74': U.S. Minor Outlying Islands
    '78': Virgin Islands
